libfreenect 0.5.4
needed to fix

```
  OpenNI2-FreenectDriver/src/VideoStream.hpp:55:31: error: call to 'abs'
  is ambiguous
  uint64_t temp_delta = std::abs(timestamp - prev_int);
```

Closes #4266.

Signed-off-by: ilovezfs <ilovezfs@icloud.com>